import pandas as pd
import numpy as np
import os
import json

# ------------------------------------------------------------
# Load settings
# ------------------------------------------------------------
with open("configs/settings.json", "r") as f:
    SETTINGS = json.load(f)

PAIRS = SETTINGS["pairs"]
DATA_DIR = "data"

# ------------------------------------------------------------
# Create output directory
# ------------------------------------------------------------
os.makedirs("data", exist_ok=True)

# ------------------------------------------------------------
# Feature Engineering Function
# ------------------------------------------------------------
def process_pair(pair):
    try:
        path = f"{DATA_DIR}/{pair}.parquet"
        if not os.path.exists(path):
            print(f"⚠ File not found for {pair}")
            return

        df = pd.read_parquet(path)

        # Ensure timestamp column exists
        if "timestamp" in df.columns:
            df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
            df = df.set_index("timestamp")
        elif "datetime" in df.columns:
            df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")
            df = df.set_index("datetime")
        else:
            print(f"⚠ {pair} missing timestamp/datetime column")
            return

        # ------------------------------------------------------------
        # FEATURE EXAMPLES
        # ------------------------------------------------------------

        # 1. Returns
        df["return"] = df["close"].pct_change()

        # 2. Volatility (rolling std)
        df["volatility"] = df["return"].rolling(20).std()

        # 3. Moving averages
        df["ma_10"] = df["close"].rolling(10).mean()
        df["ma_20"] = df["close"].rolling(20).mean()
        df["ma_50"] = df["close"].rolling(50).mean()

        # 4. RSI
        delta = df["close"].diff()
        gain = (delta.where(delta > 0, 0)).rolling(14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(14).mean()
        rs = gain / loss
        df["rsi"] = 100 - (100 / (1 + rs))

        # 5. Hour & minute features
        df["hour"] = df.index.hour
        df["minute"] = df.index.minute
        df["dayofweek"] = df.index.dayofweek

        # Drop NaN rows generated by rolling windows
        df = df.dropna()

        # Save processed file
        out_path = f"data/processed_{pair}.parquet"
        df.to_parquet(out_path)

        print(f"✔ Saved processed to {out_path}")

    except Exception as e:
        print(f"Failed {pair}: {e}")


# ------------------------------------------------------------
# MAIN
# ------------------------------------------------------------
if __name__ == "__main__":
    for pair in PAIRS:
        print(f"Processing {pair}")
        process_pair(pair)
